services:
  api:
    build: ./api
    ports:
      - 8000:8000
    volumes:
        - ./api:/app
    tty: true
    environment:
      - MONGODB_URL=mongodb://mongo:mongo@mongodb/
      - DATABASE=acropyx2-dev
      - __MONGODB_URL=mongodb+srv://acroworldtour:twuR2iO70dzTFWPVb84Q@mongodb-c59cc3c1-oc9ba1bd0.database.cloud.ovh.net/acroworldtour?replicaSet=replicaset&tls=true&authSource=admin
      - __DATABASE=acroworldtour
      - CACHE_EXPIRES=0
      - _REDIS_URL=redis://redis:6379
      - LOG_LEVEL=DEBUG
#      - SERVER_HOST=http://172.17.0.1:8000

  manager:
    image: node:20-alpine
    command: sh -c "npm install -g pnpm && pnpm install && pnpm run dev"
    working_dir: /app
    ports:
      - 3001:3001
    volumes:
      - ./manager:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://127.0.0.1:8000
#      - NEXT_PUBLIC_API_URL=https://api.acroworldtour.com
      - NEXT_PUBLIC_BORDER_COLOR=blueviolet
      - NEXT_TELEMETRY_DISABLED=1

  results:
    image: node:20-alpine
    command: sh -c "npm install -g pnpm && pnpm install && pnpm run dev"
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./results:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://127.0.0.1:8000/public
#      - NEXT_PUBLIC_API_URL=https://api.acroworldtour.com/public
      - NEXT_CACHE_DURATION=1
      - NEXT_TELEMETRY_DISABLED=1

  www:
    image: nginx
    ports:
      - 3002:80
    volumes:
      - ./www:/usr/share/nginx/html:ro
      - ./utils/nginx.vhost.www.conf:/etc/nginx/conf.d/default.conf:ro

  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    command: --setParameter processUmask=022
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
